/**
 * 已知植物缓存数据（26 种）
 * 用于快速返回，避免重复调用 AI
 */

module.exports = {
  // ========== 新手友好 - 职场办公 ==========
  '绿萝': {
    success: true,
    name: '绿萝',
    commonNames: '魔鬼藤、黄金葛、绿萝海棠',
    scientificName: '绿萝',
    scientificNameLatin: 'Epipremnum aureum',
    family: '天南星科、绿萝属',
    origin: '印度尼西亚、所罗门群岛，现广泛分布于热带地区',
    plantProfile: '绿萝是常见的室内观叶植物，叶片心形翠绿，四季常青。生长迅速，适应性强，能有效净化空气中的甲醛、苯等有害物质，被誉为"天然空气净化器"。',
    growthHabit: '喜温暖湿润的半阴环境，不耐寒，忌强光直射。生长适温 15-25℃，冬季不低于 10℃。',
    mainValue: '观赏价值高，净化空气能力强，适合办公室和家居摆放。',
    careGuide: {
      light: '喜散射光，避免阳光直射，可放在室内明亮处或北阳台',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天浇一次，见干见湿',
      temperature: '适宜温度 15-25℃，冬季保持 10℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水增湿',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，冬季停止施肥',
      soil: '疏松肥沃、排水良好的腐叶土或泥炭土',
      pruning: '及时剪除黄叶、枯叶，促进新枝萌发',
      propagation: '扦插繁殖，剪取带气根的枝条水培或土培，极易成活'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，几乎养不死',
    quickTips: ['避免阳光直射', '保持土壤湿润', '定期擦拭叶片', '可水培可土培'],
    commonProblems: ['叶片发黄：浇水过多或光照不足，控制浇水并增加散射光', '叶尖干枯：空气干燥，向叶面喷水增湿', '长势缓慢：缺肥，生长期每月施肥 1-2 次'],
    imageUrl: 'cloud://plant-encyclopedia-8d9x10139590b.706c-plant-encyclopedia-8d9x10139590b-1416656727/plant-images/categories/lvluo.png'
  },
  
  '虎皮兰': {
    success: true,
    name: '虎皮兰',
    commonNames: '虎尾兰、千岁兰、虎皮掌',
    scientificName: '虎尾兰',
    scientificNameLatin: 'Sansevieria trifasciata',
    family: '天门冬科、虎尾兰属',
    origin: '非洲西部和南部，现广泛栽培于热带和亚热带地区',
    plantProfile: '虎皮兰叶片挺拔直立，表面有灰白和深绿相间的虎尾状横纹，观赏价值高。夜间释放氧气，吸收二氧化碳，适合卧室摆放。',
    growthHabit: '喜温暖干燥、阳光充足的环境，耐干旱，不耐水湿。生长适温 20-30℃。',
    mainValue: '观赏性强，夜间释氧，净化空气，吸收甲醛和苯。',
    careGuide: {
      light: '喜阳光，也耐阴，可放在室内明亮处或阳台',
      water: '耐旱，土壤干透再浇水，夏季 7-10 天一次，冬季 15-20 天一次',
      temperature: '适宜温度 20-30℃，冬季保持 10℃以上',
      humidity: '耐干燥，不需特别增湿',
      fertilizer: '生长期每月施 1 次稀薄液肥，冬季停止施肥',
      soil: '疏松透气、排水良好的沙质土壤',
      pruning: '及时剪除老化叶片，保持株型美观',
      propagation: '分株或叶插繁殖，叶插时叶片切成小段插入沙土中'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，耐旱耐贫瘠',
    quickTips: ['宁干勿湿', '多晒太阳', '冬季少浇水', '可吸收甲醛'],
    commonProblems: ['叶片发软：浇水过多，控制浇水并保持通风', '叶片倒伏：光照不足，增加光照或人工补光', '根茎腐烂：积水导致，切除腐烂部分重新扦插'],
    imageUrl: ''
  },
  
  '文竹': {
    success: true,
    name: '文竹',
    commonNames: '云片竹、山草、鸡绒芝',
    scientificName: '文竹',
    scientificNameLatin: 'Asparagus setaceus',
    family: '天门冬科、天门冬属',
    origin: '非洲南部，现广泛栽培于世界各地',
    plantProfile: '文竹枝叶纤细秀丽，层次分明，如云似雾，具有浓郁的书香气息。适合摆放在书房、办公室，增添文雅氛围。',
    growthHabit: '喜温暖湿润的半阴环境，不耐寒，忌强光直射和干燥。生长适温 15-25℃。',
    mainValue: '观赏价值高，增添文雅气息，适合书房和办公室摆放。',
    careGuide: {
      light: '喜散射光，避免阳光直射，可放在室内明亮处',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次，经常向叶面喷水',
      temperature: '适宜温度 15-25℃，冬季保持 5℃以上',
      humidity: '喜湿润环境，干燥时向叶面和周围喷水增湿',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，以氮肥为主',
      soil: '疏松肥沃、排水良好的腐叶土',
      pruning: '及时剪除枯黄枝叶，促进新枝萌发',
      propagation: '播种或分株繁殖，春季播种易发芽'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['避免阳光直射', '保持空气湿润', '定期喷水', '以氮肥为主'],
    commonProblems: ['叶片发黄：空气干燥或光照过强，增加湿度并避免直射光', '枝叶干枯：浇水不足，保持土壤湿润', '长势缓慢：缺肥，生长期每月施肥'],
    imageUrl: ''
  },
  
  '仙人掌': {
    success: true,
    name: '仙人掌',
    commonNames: '仙巴掌、观音掌',
    scientificName: '仙人掌',
    scientificNameLatin: 'Cactaceae',
    family: '仙人掌科、仙人掌属',
    origin: '美洲热带和亚热带地区，现广泛栽培于世界各地',
    plantProfile: '仙人掌形态独特，茎肉质多浆，表面有刺或毛。耐旱性极强，适合忙碌的上班族养护。据说能减少电脑辐射。',
    growthHabit: '喜温暖干燥、阳光充足的环境，极耐干旱，不耐寒。生长适温 20-30℃。',
    mainValue: '观赏性强，耐旱易养，据说能减少电磁辐射。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或窗台',
      water: '极耐旱，土壤完全干透再浇水，夏季 10-15 天一次，冬季 20-30 天一次',
      temperature: '适宜温度 20-30℃，冬季保持 5℃以上',
      humidity: '耐干燥，不需增湿',
      fertilizer: '生长期每月施 1 次稀薄液肥，冬季停止施肥',
      soil: '疏松透气、排水良好的沙质土壤或专用仙人掌土',
      pruning: '及时剪除腐烂或老化部分，注意防刺',
      propagation: '扦插繁殖，切取侧枝晾干后插入沙土中'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，极耐干旱',
    quickTips: ['宁干勿湿', '多晒太阳', '冬季断水', '注意防刺'],
    commonProblems: ['茎部发软：浇水过多，控制浇水并通风', '根茎腐烂：积水导致，切除腐烂部分重新扦插', '徒长：光照不足，增加光照'],
    imageUrl: ''
  },
  
  '吊兰': {
    success: true,
    name: '吊兰',
    commonNames: '桂兰、折鹤兰、空气卫士',
    scientificName: '吊兰',
    scientificNameLatin: 'Chlorophytum comosum',
    family: '天门冬科、吊兰属',
    origin: '非洲南部，现广泛栽培于世界各地',
    plantProfile: '吊兰叶片细长柔软，从叶腋中抽生出小植株，四季常绿。能吸收空气中的甲醛、一氧化碳等有害气体，被誉为"空气卫士"。',
    growthHabit: '喜温暖湿润的半阴环境，适应性强，耐寒耐旱。生长适温 15-25℃。',
    mainValue: '净化空气能力强，观赏价值高，易于养护。',
    careGuide: {
      light: '喜散射光，避免强光直射，可放在室内明亮处',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 5℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1-2 次稀薄液肥',
      soil: '疏松肥沃、排水良好的腐叶土',
      pruning: '及时剪除枯黄叶片和走茎上老化的小植株',
      propagation: '分株或扦插走茎上的小植株，极易成活'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，适应性强',
    quickTips: ['保持土壤湿润', '避免强光直射', '定期修剪', '可吸收甲醛'],
    commonProblems: ['叶尖干枯：空气干燥，向叶面喷水增湿', '叶片发黄：浇水过多或光照过强，控制浇水并避免直射光', '长势缓慢：缺肥，生长期每月施肥'],
    imageUrl: ''
  },
  
  '富贵竹': {
    success: true,
    name: '富贵竹',
    commonNames: '万年竹、开运竹、富贵塔',
    scientificName: '富贵竹',
    scientificNameLatin: 'Dracaena sanderiana',
    family: '天门冬科、龙血树属',
    origin: '非洲西部和南部，现广泛栽培于热带地区',
    plantProfile: '富贵竹茎叶纤秀，柔美优雅，极富竹韵。寓意吉祥，招财进宝，可水培可土培，适合家居和办公室摆放。',
    growthHabit: '喜温暖湿润的半阴环境，耐阴，不耐寒。生长适温 20-28℃。',
    mainValue: '观赏价值高，寓意吉祥，可水培易养护。',
    careGuide: {
      light: '喜散射光，避免强光直射，可放在室内明亮处',
      water: '水培：保持水质清洁，7-10 天换水一次；土培：保持土壤湿润',
      temperature: '适宜温度 20-28℃，冬季保持 10℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '水培：每月加 1-2 滴营养液；土培：每月施 1 次稀薄液肥',
      soil: '水培或疏松肥沃、排水良好的土壤',
      pruning: '及时剪除黄叶，保持株型美观',
      propagation: '扦插繁殖，剪取茎段插入水中或沙土中'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，水培易养',
    quickTips: ['水培保持水质清洁', '避免阳光直射', '定期换水', '寓意吉祥'],
    commonProblems: ['叶片发黄：水质不好或光照过强，换水并避免直射光', '根茎腐烂：水质污染，换水并清洗根部', '长势缓慢：缺肥，定期加营养液'],
    imageUrl: ''
  },
  
  // ========== 新手友好 - 宠物友好 ==========
  '竹芋': {
    success: true,
    name: '竹芋',
    commonNames: '竹芋科植物',
    scientificName: '竹芋',
    scientificNameLatin: 'Calathea',
    family: '竹芋科、竹芋属',
    origin: '美洲热带地区，现广泛栽培于热带和亚热带地区',
    plantProfile: '竹芋叶片宽大，色彩斑斓，叶面有美丽的斑纹和光泽。叶片夜间闭合，白天展开，非常有趣。对宠物安全无毒。',
    growthHabit: '喜温暖湿润的半阴环境，不耐寒，忌强光直射。生长适温 18-25℃。',
    mainValue: '观赏价值高，对宠物安全，适合多宠家庭。',
    careGuide: {
      light: '喜散射光，避免阳光直射，可放在室内明亮处',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次',
      temperature: '适宜温度 18-25℃，冬季保持 15℃以上',
      humidity: '喜高湿环境，经常向叶面和周围喷水增湿',
      fertilizer: '生长期每月施 1-2 次稀薄液肥',
      soil: '疏松肥沃、排水良好的腐叶土',
      pruning: '及时剪除枯黄叶片，保持株型美观',
      propagation: '分株繁殖，春季换盆时进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['保持高湿度', '避免阳光直射', '对宠物安全', '叶片夜间闭合'],
    commonProblems: ['叶缘焦枯：空气干燥，增加湿度并经常喷水', '叶片卷曲：光照过强或湿度不足，避免直射光并增湿', '叶色变淡：缺肥，生长期定期施肥'],
    imageUrl: ''
  },
  
  '空气凤梨': {
    success: true,
    name: '空气凤梨',
    commonNames: '铁兰花、空气草',
    scientificName: '空气凤梨',
    scientificNameLatin: 'Tillandsia',
    family: '凤梨科、空气凤梨属',
    origin: '美洲热带和亚热带地区',
    plantProfile: '空气凤梨无需土壤，直接从空气中吸收水分和养分，可悬挂或摆放在任意位置。形态多样，色彩丰富，对宠物安全。',
    growthHabit: '喜温暖湿润、通风良好的环境，耐旱，不耐寒。生长适温 15-25℃。',
    mainValue: '无需土壤，养护简单，对宠物安全，装饰性强。',
    careGuide: {
      light: '喜明亮散射光，避免强光直射',
      water: '每周喷水 2-3 次或浸泡 10 分钟，保持通风',
      temperature: '适宜温度 15-25℃，冬季保持 10℃以上',
      humidity: '喜湿润环境，干燥时增加喷水频率',
      fertilizer: '每月喷施 1 次稀薄液肥',
      soil: '无需土壤，可悬挂或摆放在支架上',
      pruning: '及时剪除枯叶和凋谢的花序',
      propagation: '分株繁殖，母株基部萌发的小株分离后单独养护'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['无需土壤', '每周喷水 2-3 次', '保持通风', '对宠物安全'],
    commonProblems: ['叶片干枯：湿度不足，增加喷水频率', '根茎腐烂：通风不良，加强通风并减少喷水', '长势缓慢：缺肥，定期喷施液肥'],
    imageUrl: ''
  },
  
  '波士顿蕨': {
    success: true,
    name: '波士顿蕨',
    commonNames: '肾蕨、蜈蚣草',
    scientificName: '波士顿蕨',
    scientificNameLatin: 'Nephrolepis exaltata',
    family: '肾蕨科、肾蕨属',
    origin: '美洲热带地区，现广泛栽培于世界各地',
    plantProfile: '波士顿蕨叶片翠绿，羽状复叶优雅下垂，姿态优美。能有效增加空气湿度，净化空气，对宠物安全。',
    growthHabit: '喜温暖湿润的半阴环境，不耐寒，忌强光直射。生长适温 15-25℃。',
    mainValue: '观赏价值高，增加空气湿度，对宠物安全。',
    careGuide: {
      light: '喜散射光，避免阳光直射，可放在室内明亮处',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 10℃以上',
      humidity: '喜高湿环境，经常向叶面和周围喷水增湿',
      fertilizer: '生长期每月施 1-2 次稀薄液肥',
      soil: '疏松肥沃、排水良好的腐叶土',
      pruning: '及时剪除枯黄叶片，保持株型美观',
      propagation: '分株繁殖，春季换盆时进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['保持土壤湿润', '保持高湿度', '避免阳光直射', '对宠物安全'],
    commonProblems: ['叶尖干枯：空气干燥，增加湿度并经常喷水', '叶片发黄：浇水过多或光照过强，控制浇水并避免直射光', '长势缓慢：缺肥，生长期定期施肥'],
    imageUrl: ''
  },
  
  '蜘蛛抱蛋': {
    success: true,
    name: '蜘蛛抱蛋',
    commonNames: '一叶兰、大叶万年青',
    scientificName: '蜘蛛抱蛋',
    scientificNameLatin: 'Aspidistra elatior',
    family: '天门冬科、蜘蛛抱蛋属',
    origin: '中国南部、日本和越南',
    plantProfile: '蜘蛛抱蛋叶片宽大浓绿，四季常青，生命力强。极耐阴，适合室内光线不好的地方摆放，对宠物安全。',
    growthHabit: '喜温暖湿润的半阴环境，极耐阴，不耐寒。生长适温 15-25℃。',
    mainValue: '极耐阴，生命力强，对宠物安全，适合室内摆放。',
    careGuide: {
      light: '耐阴，可放在室内光线较暗处，避免强光直射',
      water: '保持土壤湿润，夏季 3-5 天浇水一次，冬季 7-10 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 5℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1 次稀薄液肥',
      soil: '疏松肥沃、排水良好的腐叶土',
      pruning: '及时剪除枯黄叶片，保持株型美观',
      propagation: '分株繁殖，春季换盆时进行'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，极耐阴',
    quickTips: ['极耐阴', '保持土壤湿润', '对宠物安全', '生命力强'],
    commonProblems: ['叶片发黄：浇水过多或光照过强，控制浇水并避免直射光', '叶尖干枯：空气干燥，向叶面喷水增湿', '长势缓慢：缺肥，生长期定期施肥'],
    imageUrl: ''
  },
  
  '圆叶椒草': {
    success: true,
    name: '圆叶椒草',
    commonNames: '豆瓣绿、圆叶豆瓣绿',
    scientificName: '圆叶椒草',
    scientificNameLatin: 'Peperomia obtusifolia',
    family: '胡椒科、椒草属',
    origin: '美洲热带地区',
    plantProfile: '圆叶椒草叶片圆润厚实，翠绿有光泽，小巧可爱。对宠物安全无毒，适合桌面摆放。',
    growthHabit: '喜温暖湿润的半阴环境，不耐寒，忌强光直射。生长适温 18-25℃。',
    mainValue: '观赏价值高，小巧可爱，对宠物安全。',
    careGuide: {
      light: '喜散射光，避免阳光直射，可放在室内明亮处',
      water: '保持土壤微湿，夏季 3-5 天浇水一次，冬季 7-10 天一次',
      temperature: '适宜温度 18-25℃，冬季保持 15℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1 次稀薄液肥',
      soil: '疏松肥沃、排水良好的腐叶土',
      pruning: '及时剪除枯黄叶片，促进新枝萌发',
      propagation: '叶插或茎插繁殖，极易成活'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['保持土壤微湿', '避免阳光直射', '对宠物安全', '可叶插繁殖'],
    commonProblems: ['叶片发软：浇水过多，控制浇水并通风', '叶色变淡：光照不足，增加散射光', '长势缓慢：缺肥，生长期定期施肥'],
    imageUrl: ''
  },
  
  '金钱树': {
    success: true,
    name: '金钱树',
    commonNames: '雪铁芋、泽米叶天南星',
    scientificName: '金钱树',
    scientificNameLatin: 'Zamioculcas zamiifolia',
    family: '天门冬科、雪铁芋属',
    origin: '非洲东部',
    plantProfile: '金钱树叶片像一串串铜钱，翠绿有光泽，寓意美好。耐旱耐阴，易于养护，对宠物有轻微毒性，需放置在宠物接触不到的地方。',
    growthHabit: '喜温暖干燥的半阴环境，耐旱，不耐寒。生长适温 20-30℃。',
    mainValue: '观赏价值高，寓意美好，耐旱易养。',
    careGuide: {
      light: '喜散射光，避免强光直射，可放在室内明亮处',
      water: '耐旱，土壤干透再浇水，夏季 7-10 天一次，冬季 15-20 天一次',
      temperature: '适宜温度 20-30℃，冬季保持 10℃以上',
      humidity: '耐干燥，不需特别增湿',
      fertilizer: '生长期每月施 1 次稀薄液肥',
      soil: '疏松透气、排水良好的沙质土壤',
      pruning: '及时剪除黄叶，保持株型美观',
      propagation: '分株或叶插繁殖，叶插时叶片插入沙土中'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['宁干勿湿', '避免强光直射', '注意宠物安全', '寓意美好'],
    commonProblems: ['块茎腐烂：浇水过多，控制浇水并通风', '叶片发黄：浇水过多或光照过强，控制浇水并避免直射光', '长势缓慢：缺肥，生长期定期施肥'],
    imageUrl: ''
  },
  
  // ========== 新手友好 - 老人适合 ==========
  '长寿花': {
    success: true,
    name: '长寿花',
    commonNames: '圣诞伽蓝菜、寿星花',
    scientificName: '长寿花',
    scientificNameLatin: 'Kalanchoe blossfeldiana',
    family: '景天科、伽蓝菜属',
    origin: '非洲马达加斯加',
    plantProfile: '长寿花叶片肥厚翠绿，花朵密集，色彩丰富，花期超长。寓意健康长寿，适合送给长辈。',
    growthHabit: '喜温暖干燥、阳光充足的环境，耐干旱，不耐寒。生长适温 15-25℃。',
    mainValue: '观赏价值高，花期长，寓意健康长寿。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或窗台',
      water: '耐旱，土壤干透再浇水，夏季 5-7 天一次，冬季 10-15 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 10℃以上',
      humidity: '耐干燥，不需特别增湿',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，花期前增施磷钾肥',
      soil: '疏松透气、排水良好的沙质土壤',
      pruning: '花后及时修剪残花和徒长枝，促进分枝',
      propagation: '扦插繁殖，剪取枝条晾干后插入沙土中'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，耐旱易养',
    quickTips: ['多晒太阳', '宁干勿湿', '花前施磷钾肥', '寓意健康长寿'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加光照并施磷钾肥', '叶片发软：浇水过多，控制浇水并通风', '徒长：光照不足，增加光照'],
    imageUrl: ''
  },
  
  '芦荟': {
    success: true,
    name: '芦荟',
    commonNames: '库拉索芦荟、油葱',
    scientificName: '芦荟',
    scientificNameLatin: 'Aloe vera',
    family: '阿福花科、芦荟属',
    origin: '非洲北部，现广泛栽培于热带地区',
    plantProfile: '芦荟叶片肥厚多汁，边缘有小刺。具有美容、护肤、药用等多种功效，易于养护。',
    growthHabit: '喜温暖干燥、阳光充足的环境，极耐干旱，不耐寒。生长适温 20-30℃。',
    mainValue: '观赏、美容、药用于一体，耐旱易养。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或窗台',
      water: '极耐旱，土壤完全干透再浇水，夏季 7-10 天一次，冬季 15-20 天一次',
      temperature: '适宜温度 20-30℃，冬季保持 10℃以上',
      humidity: '耐干燥，不需增湿',
      fertilizer: '生长期每月施 1 次稀薄液肥',
      soil: '疏松透气、排水良好的沙质土壤',
      pruning: '及时剪除底部老化叶片',
      propagation: '分株繁殖，母株基部萌发的小株分离后单独养护'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，极耐干旱',
    quickTips: ['宁干勿湿', '多晒太阳', '可美容护肤', '冬季少浇水'],
    commonProblems: ['叶片发软：浇水过多，控制浇水并通风', '根茎腐烂：积水导致，切除腐烂部分重新扦插', '徒长：光照不足，增加光照'],
    imageUrl: ''
  },
  
  '君子兰': {
    success: true,
    name: '君子兰',
    commonNames: '大花君子兰',
    scientificName: '君子兰',
    scientificNameLatin: 'Clivia miniata',
    family: '石蒜科、君子兰属',
    origin: '非洲南部',
    plantProfile: '君子兰叶片宽厚，排列整齐，花朵艳丽，象征高尚品格。花期长，适合室内摆放。',
    growthHabit: '喜温暖湿润的半阴环境，不耐寒，忌强光直射。生长适温 15-25℃。',
    mainValue: '观赏价值高，象征高尚品格，花期长。',
    careGuide: {
      light: '喜散射光，避免阳光直射，可放在室内明亮处',
      water: '保持土壤湿润，夏季 3-5 天浇水一次，冬季 7-10 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 10℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，花期前增施磷钾肥',
      soil: '疏松肥沃、排水良好的腐叶土',
      pruning: '及时剪除枯黄叶片和残花',
      propagation: '分株或播种繁殖，分株在春季换盆时进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['避免阳光直射', '保持土壤湿润', '花前施磷钾肥', '象征高尚品格'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加散射光并施磷钾肥', '叶片发黄：浇水过多或光照过强，控制浇水并避免直射光', '烂根：积水导致，控制浇水并通风'],
    imageUrl: ''
  },
  
  '万年青': {
    success: true,
    name: '万年青',
    commonNames: '开口箭、冬不凋草',
    scientificName: '万年青',
    scientificNameLatin: 'Rohdea japonica',
    family: '天门冬科、万年青属',
    origin: '中国、日本',
    plantProfile: '万年青叶片宽大浓绿，四季常青，生命力强。寓意健康长寿，四季常青，适合送给长辈。',
    growthHabit: '喜温暖湿润的半阴环境，耐阴，不耐寒。生长适温 15-25℃。',
    mainValue: '观赏价值高，寓意健康长寿，生命力强。',
    careGuide: {
      light: '喜散射光，避免强光直射，可放在室内明亮处',
      water: '保持土壤湿润，夏季 3-5 天浇水一次，冬季 7-10 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 5℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1-2 次稀薄液肥',
      soil: '疏松肥沃、排水良好的腐叶土',
      pruning: '及时剪除枯黄叶片，保持株型美观',
      propagation: '分株繁殖，春季换盆时进行'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手，生命力强',
    quickTips: ['保持土壤湿润', '避免强光直射', '寓意健康长寿', '四季常青'],
    commonProblems: ['叶片发黄：浇水过多或光照过强，控制浇水并避免直射光', '叶尖干枯：空气干燥，向叶面喷水增湿', '长势缓慢：缺肥，生长期定期施肥'],
    imageUrl: ''
  },
  
  // ========== 新手友好 - 开花植物 ==========
  '蝴蝶兰': {
    success: true,
    name: '蝴蝶兰',
    commonNames: '蝶兰',
    scientificName: '蝴蝶兰',
    scientificNameLatin: 'Phalaenopsis aphrodite',
    family: '兰科、蝴蝶兰属',
    origin: '东南亚热带地区',
    plantProfile: '蝴蝶兰花形如蝴蝶飞舞，花色丰富，花期长达数月，被誉为"花中皇后"。高雅华贵，适合室内摆放。',
    growthHabit: '喜温暖湿润的半阴环境，不耐寒，忌强光直射。生长适温 18-28℃。',
    mainValue: '观赏价值极高，花期长，高雅华贵。',
    careGuide: {
      light: '喜散射光，避免阳光直射，可放在室内明亮处',
      water: '保持介质微湿，夏季 5-7 天浇水一次，冬季 10-15 天一次',
      temperature: '适宜温度 18-28℃，冬季保持 15℃以上',
      humidity: '喜高湿环境，经常向周围喷水增湿',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，花期前增施磷钾肥',
      soil: '水苔或树皮等专用兰花介质',
      pruning: '花后及时剪除花梗，促进新花芽萌发',
      propagation: '分株或组织培养繁殖'
    },
    difficultyLevel: 3,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['避免阳光直射', '保持高湿度', '花前施磷钾肥', '花期长达数月'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加散射光并施磷钾肥', '叶片发黄：浇水过多或光照过强，控制浇水并避免直射光', '烂根：积水导致，控制浇水并通风'],
    imageUrl: 'cloud://plant-encyclopedia-8d9x10139590b.706c-plant-encyclopedia-8d9x10139590b-1416656727/plant-images/categories/hudielan.png'
  },
  
  '发财树': {
    success: true,
    name: '发财树',
    commonNames: '马拉巴栗、瓜栗',
    scientificName: '发财树',
    scientificNameLatin: 'Pachira aquatica',
    family: '木棉科、瓜栗属',
    origin: '中美洲、南美洲',
    plantProfile: '发财树树干挺拔，叶片翠绿，寓意吉祥如意、财源广进。适合室内摆放，净化空气。',
    growthHabit: '喜温暖湿润、阳光充足的环境，不耐寒，耐半阴。生长适温 20-30℃。',
    mainValue: '观赏价值高，寓意吉祥，可净化空气。',
    careGuide: {
      light: '喜充足散射光，避免强光直射',
      water: '保持土壤微湿，夏季 3-5 天浇水一次，冬季 7-10 天一次',
      temperature: '适宜温度 20-30℃，冬季保持 10℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1 次稀薄液肥',
      soil: '疏松肥沃、排水良好的沙质土壤',
      pruning: '及时修剪徒长枝和病弱枝，保持株型美观',
      propagation: '扦插或播种繁殖，春季进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合新手养护',
    quickTips: ['避免强光直射', '冬季注意保暖', '定期修剪整形', '寓意财源广进'],
    commonProblems: ['叶片发黄：浇水过多或光照不足，控制浇水并增加散射光', '树干发软：烂根，控制浇水并通风', '落叶：温度过低或环境突变，保持温度稳定'],
    imageUrl: 'cloud://plant-encyclopedia-8d9x10139590b.706c-plant-encyclopedia-8d9x10139590b-1416656727/plant-images/categories/facaishu.png'
  },
  
  '栀子花': {
    success: true,
    name: '栀子花',
    commonNames: '黄栀子、山栀',
    scientificName: '栀子花',
    scientificNameLatin: 'Gardenia jasminoides',
    family: '茜草科、栀子属',
    origin: '中国、日本',
    plantProfile: '栀子花花朵洁白素雅，花香浓郁，清香四溢。适合庭院或阳台种植，花期 5-7 月。',
    growthHabit: '喜温暖湿润、阳光充足的环境，不耐寒，喜酸性土壤。生长适温 15-25℃。',
    mainValue: '观赏价值高，花香浓郁，可提取香精。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或庭院',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 5℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，喜酸性肥料',
      soil: '疏松肥沃、排水良好的酸性土壤',
      pruning: '花后及时修剪残花和徒长枝，促进分枝',
      propagation: '扦插或压条繁殖，春季进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['多晒太阳', '保持土壤湿润', '喜酸性土壤', '花香浓郁'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加光照并施磷钾肥', '叶片发黄：土壤碱性或缺铁，施用硫酸亚铁', '花蕾掉落：浇水过多或过少，保持土壤湿润'],
    imageUrl: ''
  },
  
  '茉莉花': {
    success: true,
    name: '茉莉花',
    commonNames: '茉莉、抹莉',
    scientificName: '茉莉花',
    scientificNameLatin: 'Jasminum sambac',
    family: '木犀科、素馨属',
    origin: '印度、阿拉伯',
    plantProfile: '茉莉花花朵洁白，香气袭人，芬芳迷人。可泡茶、提取香精，花期 5-10 月。',
    growthHabit: '喜温暖湿润、阳光充足的环境，不耐寒。生长适温 20-30℃。',
    mainValue: '观赏价值高，花香浓郁，可泡茶。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或庭院',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次',
      temperature: '适宜温度 20-30℃，冬季保持 10℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，花期前增施磷钾肥',
      soil: '疏松肥沃、排水良好的微酸性土壤',
      pruning: '花后及时修剪残花和徒长枝，促进分枝',
      propagation: '扦插繁殖，春季或梅雨季节进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['多晒太阳', '保持土壤湿润', '花前施磷钾肥', '花香浓郁可泡茶'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加光照并施磷钾肥', '叶片发黄：土壤碱性或缺铁，施用硫酸亚铁', '花蕾掉落：浇水过多或过少，保持土壤湿润'],
    imageUrl: ''
  },
  
  '茉莉': {
    success: true,
    name: '茉莉',
    commonNames: '茉莉花、抹莉',
    scientificName: '茉莉花',
    scientificNameLatin: 'Jasminum sambac',
    family: '木犀科、素馨属',
    origin: '印度、阿拉伯',
    plantProfile: '茉莉花花朵洁白，香气袭人，芬芳迷人。可泡茶、提取香精，花期 5-10 月。',
    growthHabit: '喜温暖湿润、阳光充足的环境，不耐寒。生长适温 20-30℃。',
    mainValue: '观赏价值高，花香浓郁，可泡茶。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或庭院',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次',
      temperature: '适宜温度 20-30℃，冬季保持 10℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，花期前增施磷钾肥',
      soil: '疏松肥沃、排水良好的微酸性土壤',
      pruning: '花后及时修剪残花和徒长枝，促进分枝',
      propagation: '扦插繁殖，春季或梅雨季节进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['多晒太阳', '保持土壤湿润', '花前施磷钾肥', '花香浓郁可泡茶'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加光照并施磷钾肥', '叶片发黄：土壤碱性或缺铁，施用硫酸亚铁', '花蕾掉落：浇水过多或过少，保持土壤湿润'],
    imageUrl: 'cloud://plant-encyclopedia-8d9x10139590b.706c-plant-encyclopedia-8d9x10139590b-1416656727/plant-images/categories/molihua.png'
  },
  
  '多肉': {
    success: true,
    name: '多肉',
    commonNames: '多肉植物、多浆植物',
    scientificName: 'Succulent',
    scientificNameLatin: 'Succulent',
    family: '多肉植物科',
    origin: '全球各地',
    plantProfile: '多肉植物叶片肥厚多汁，形态多样，色彩丰富。耐旱易养，适合新手，品种超过 1 万种。',
    growthHabit: '喜阳光充足、干燥通风的环境，不耐寒，怕积水。生长适温 15-25℃。',
    mainValue: '观赏价值高，品种丰富，易于养护，适合桌面摆放。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台，夏季适当遮阴',
      water: '宁干勿湿，土壤干透再浇水，夏季 7-10 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 5℃以上',
      humidity: '喜干燥环境，避免高湿，保持通风',
      fertilizer: '生长期每月施 1 次稀薄液肥，夏季和冬季停肥',
      soil: '疏松透气、排水良好的颗粒土或多肉专用土',
      pruning: '及时清理枯叶，徒长时可砍头繁殖',
      propagation: '叶插、扦插或分株繁殖，春秋季节最佳'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手养护',
    quickTips: ['多晒太阳少浇水', '土壤干透再浇', '夏季注意遮阴', '冬季注意保暖'],
    commonProblems: ['叶片化水：浇水过多或通风不良，控制浇水并加强通风', '徒长：光照不足，增加光照或补光灯', '黑腐：真菌感染，切除腐烂部分并消毒'],
    imageUrl: 'cloud://plant-encyclopedia-8d9x10139590b.706c-plant-encyclopedia-8d9x10139590b-1416656727/plant-images/categories/duorou.png'
  },
  
  '龟背竹': {
    success: true,
    name: '龟背竹',
    commonNames: '龟背蕉、蓬莱蕉',
    scientificName: '龟背竹',
    scientificNameLatin: 'Monstera deliciosa',
    family: '天南星科、龟背竹属',
    origin: '墨西哥、巴拿马',
    plantProfile: '龟背竹叶片巨大，有独特的孔裂，形似龟背，极具观赏性。耐阴易养，适合室内摆放。',
    growthHabit: '喜温暖湿润、半阴的环境，不耐寒，忌强光直射。生长适温 20-30℃。',
    mainValue: '观赏价值高，叶片独特，可净化空气，吸收甲醛。',
    careGuide: {
      light: '喜明亮散射光，避免强光直射，可放在北向或东向',
      water: '保持土壤湿润，夏季 2-3 天浇水一次，冬季 5-7 天一次',
      temperature: '适宜温度 20-30℃，冬季保持 10℃以上',
      humidity: '喜高湿环境，定期向叶面喷水增湿',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，冬季停肥',
      soil: '疏松肥沃、排水良好的腐叶土或泥炭土',
      pruning: '及时修剪黄叶和老叶，保持株型美观',
      propagation: '扦插或分株繁殖，春季进行'
    },
    difficultyLevel: 1,
    difficultyText: '非常适合新手养护',
    quickTips: ['避免阳光直射', '保持土壤湿润', '定期喷水增湿', '叶片大而美观'],
    commonProblems: ['叶片发黄：浇水过多或光照过强，控制浇水并避免直射光', '叶片无孔裂：光照不足或植株过幼，增加散射光', '烂根：积水导致，控制浇水并通风'],
    imageUrl: 'cloud://plant-encyclopedia-8d9x10139590b.706c-plant-encyclopedia-8d9x10139590b-1416656727/plant-images/categories/guibeizhu.png'
  },
  
  '天竺葵': {
    success: true,
    name: '天竺葵',
    commonNames: '石蜡红、入腊红',
    scientificName: '天竺葵',
    scientificNameLatin: 'Pelargonium',
    family: '牻牛儿苗科、天竺葵属',
    origin: '非洲南部',
    plantProfile: '天竺葵花色丰富，花量大，全年有花。适应性强，易于养护，适合阳台和庭院种植。',
    growthHabit: '喜温暖干燥、阳光充足的环境，不耐寒，忌高温高湿。生长适温 15-25℃。',
    mainValue: '观赏价值高，花期长，适应性强。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或庭院',
      water: '保持土壤微湿，夏季 3-5 天浇水一次，冬季 7-10 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 5℃以上',
      humidity: '耐干燥，不需特别增湿',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，花期前增施磷钾肥',
      soil: '疏松肥沃、排水良好的沙质土壤',
      pruning: '花后及时修剪残花和徒长枝，促进分枝',
      propagation: '扦插繁殖，春季或秋季进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['多晒太阳', '保持土壤微湿', '花前施磷钾肥', '全年有花'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加光照并施磷钾肥', '叶片发黄：浇水过多，控制浇水并通风', '徒长：光照不足，增加光照'],
    imageUrl: ''
  },
  
  '矮牵牛': {
    success: true,
    name: '矮牵牛',
    commonNames: '碧冬茄、灵芝牡丹',
    scientificName: '矮牵牛',
    scientificNameLatin: 'Petunia',
    family: '茄科、矮牵牛属',
    origin: '南美洲',
    plantProfile: '矮牵牛花色丰富，花量大，色彩斑斓。花型如喇叭，适合花坛、阳台种植，花期长。',
    growthHabit: '喜温暖湿润、阳光充足的环境，不耐寒。生长适温 15-25℃。',
    mainValue: '观赏价值高，花色丰富，花量大。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或庭院',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次',
      temperature: '适宜温度 15-25℃，冬季保持 5℃以上',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，花期前增施磷钾肥',
      soil: '疏松肥沃、排水良好的沙质土壤',
      pruning: '花后及时修剪残花，促进新花芽萌发',
      propagation: '播种或扦插繁殖，春季播种'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['多晒太阳', '保持土壤湿润', '花前施磷钾肥', '花后及时修剪'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加光照并施磷钾肥', '叶片发黄：浇水过多，控制浇水并通风', '花量减少：缺肥，定期施肥'],
    imageUrl: ''
  },
  
  '月季': {
    success: true,
    name: '月季',
    commonNames: '月月红、长春花',
    scientificName: '月季',
    scientificNameLatin: 'Rosa chinensis',
    family: '蔷薇科、蔷薇属',
    origin: '中国',
    plantProfile: '月季花色丰富，花型优美，月月开花，花期持久。被誉为"花中皇后"，适合庭院和阳台种植。',
    growthHabit: '喜温暖湿润、阳光充足的环境，耐寒，适应性强。生长适温 15-25℃。',
    mainValue: '观赏价值极高，花期长，适应性强。',
    careGuide: {
      light: '喜充足阳光，可放在南向阳台或庭院',
      water: '保持土壤湿润，夏季每天浇水，冬季 3-5 天一次',
      temperature: '适宜温度 15-25℃，冬季可耐受 0℃低温',
      humidity: '喜湿润环境，干燥时向叶面喷水',
      fertilizer: '生长期每月施 1-2 次稀薄液肥，花期前增施磷钾肥',
      soil: '疏松肥沃、排水良好的微酸性土壤',
      pruning: '花后及时修剪残花和徒长枝，冬季重剪',
      propagation: '扦插或嫁接繁殖，春季进行'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['多晒太阳', '保持土壤湿润', '花前施磷钾肥', '月月开花'],
    commonProblems: ['只长叶不开花：光照不足或缺磷钾肥，增加光照并施磷钾肥', '叶片发黄：缺铁或浇水过多，施用硫酸亚铁并控制浇水', '病虫害：注意通风，定期喷洒杀虫剂'],
    imageUrl: ''
  },
  
  '冬瓜': {
    success: true,
    name: '冬瓜',
    commonNames: '白瓜、东瓜',
    scientificName: '冬瓜',
    scientificNameLatin: 'Benincasa hispida',
    family: '葫芦科、冬瓜属',
    origin: '中国南部、印度，现广泛种植于热带和亚热带地区',
    plantProfile: '冬瓜是一年生攀援草本植物，茎叶有粗糙毛，叶片心状肾形。果实大型，长圆柱状或近球状，表面有蜡粉。果肉白色，肉质细嫩，是夏季主要蔬菜之一。',
    growthHabit: '喜温暖湿润、阳光充足的环境，耐热不耐寒。生长适温 25-30℃，需要充足水分和肥料。',
    mainValue: '重要的夏季蔬菜，营养丰富，清热解暑。果实可食用，种子和果皮也可入药。',
    careGuide: {
      light: '喜充足阳光，需要全日照环境，每天 6-8 小时光照',
      water: '需水量大，保持土壤湿润，夏季每天浇水，早晚各一次',
      temperature: '适宜温度 25-30℃，不耐寒，低于 15℃生长缓慢',
      humidity: '喜湿润环境，空气湿度 70-80% 为宜',
      fertilizer: '生长期每 7-10 天施一次复合肥，结果期增施磷钾肥',
      soil: '疏松肥沃、排水良好的沙壤土或壤土',
      pruning: '及时摘心打顶，保留主蔓，去除侧蔓，促进结果',
      propagation: '播种繁殖，春季 3-4 月或夏季 5-6 月播种'
    },
    difficultyLevel: 2,
    difficultyText: '适合有一定经验的养护者',
    quickTips: ['需要充足阳光', '保持土壤湿润', '搭架引蔓', '人工授粉'],
    commonProblems: ['只开花不结果：需要人工授粉，上午 9-11 点进行', '叶片发黄：缺肥或浇水过多，定期施肥并控制浇水', '病虫害：注意通风，防治蚜虫和白粉病']
  }
};
